name: Waka Readme

on:
  schedule:
    # Jalan tiap jam 12 malam UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Biar bisa run manual

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          # JANGAN GANTI KODE DI BAWAH INI DENGAN KUNCI ASLI
          # Biarkan tulisannya "secrets.WAKATIME_API_KEY"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Settingan Tampilan
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_COMMIT: "True"
          SHOW_LANGUAGE: "True"
